### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by Fumler** [dayzai/A3EAI#1]
Seems you are checking for files with specific case instead of doing some sort of tolower() so this will not work on linux servers without editing.

For anyone wanting to fix this problem themselves, unpack the pbo and edit 
```A3EAI/init/A3EAI_initHC.sqf ```
```A3EAI/init/A3EAI_initserver.sqf ```

and change
```
if (isNil "A3EAI_EpochHiveDir") then {
    A3EAI_EpochHiveDir = "@EpochHive";
};
```

to

```
if (isNil "A3EAI_EpochHiveDir") then {
    A3EAI_EpochHiveDir = "@epochhive";
};
```

then repack the pbo.

**Comment by dayzai** [comment]
Change made in 0.5.8.
