### ISSUE TITLE
Underwear Patrols

### ISSUE THREAD

**Issue by briankgregory** [dayzai/A3EAI#11]
Since updating to 0.8.4 and EPOCH 0.3.2 with all the dynamic lists enabled all AI appear without backpacks or uniforms.

**Comment by briankgregory** [comment]
Setting all the dynamic lists to false seems to have no change.

**Comment by dayzai** [comment]
Redownload the latest version of A3EAI. The recent versions had a hiccup with the loadout generation but should now be fixed in 0.8.4d.

**Comment by briankgregory** [comment]
Got ya, thanks for the fast response.

**Comment by northrivergeek** [comment]
I still see ai in underware often.. even in the new version

**Comment by dayzai** [comment]
Not a bug. The A3EAI_addUniformChance0-3 settings control the probability of adding a uniform item.
