### ISSUE TITLE
Exile Mod

### ISSUE THREAD

**Issue by jus61** [dayzai/A3EAI#12]
Do you supported Exile Mod

**Comment by moosemilker** [comment]
(Heads up: This is a duplicate request - The following is dayzai's response to my request)
dayzai commented 2 days ago
Already set up my Exile test server today and the first stages of the port are under way.

The Exile port repo is currently private but will be located at: https://github.com/dayzai/A3XAI

**Comment by jus61** [comment]
Ups soory

**Comment by moosemilker** [comment]
A3XAI 1.0 has shipped.  You should consider closing this issue.

https://github.com/dayzai/A3xAI
