### ISSUE TITLE
<NOT AN ISSUE> Request to check out Exile mod for A3EAI adaption

### ISSUE THREAD

**Issue by moosemilker** [dayzai/A3EAI#9]
Not sure if you saw my message to you on opendayz.net, but...

Here is another Arma 3 mod system that would be a good match for A3EAI: http://www.exilemod.com/

It is similar to A3 EpochMod, but offers it's own building systems. They do not have AI currently, but expect server owners will add it in. Also they ship it, along with the server files this month on August 21st.  

By the A3EAI config, it should be close to working out of the box, except for krypto and maybe a few other Epoch only types of options.

Here is a stream of gameplay: https://www.youtube.com/watch?v=cwJbCbigWeU

**Comment by dayzai** [comment]
I will take a look at this mod when the server files are released. I watched about 3 minutes of the video so far and the mod looks amazingly well-done.

No guarantees right now about whether a port for the Exile mod will be made, I will try to give it a go at least.

An important thing is, if an Exile port does become a real thing, I probably won't be able to support both Epoch and Exile at once. One will be chosen over the other.

**Comment by moosemilker** [comment]
Thanks for considering it. Makes sense... If I run Exile Mod, I will also pick one or the other. It seems like it will be a wide open opportunity for excellent AI such as E3EAI. I might be your biggest fan, aside from all the people that play on my servers. :) 

Good luck in your evaluation of Exile Mod.

**Comment by moosemilker** [comment]
Closing this topic.

**Comment by moosemilker** [comment]
Reminder this is now released today.  :)  http://www.exilemod.com/download/

**Comment by dayzai** [comment]
Already set up my Exile test server today and the first stages of the port are under way.

The Exile port repo is currently private but will be located at: https://github.com/dayzai/A3XAI

**Comment by donkeypunchepoch** [comment]
As before face donkey punch is available for testing it out if need be.
Http://Github.com/donkeypunchepoch

**Comment by Rdelaura** [comment]
Please please tell me you are going with Exile and are going to release this, this week. Sounds so awesome. Thank you

**Comment by Rdelaura** [comment]
Oh and my 30 pop server would be happy to test out as well

**Comment by moosemilker** [comment]
Thank you so much for your time.

**Comment by moosemilker** [comment]
Actually, I will leave this open until the new A3XAI repo is open, since others are asking about support for ExileMod.

**Comment by taavipost** [comment]
cant wait :) i have 3 servers waiting for that!

**Comment by jus61** [comment]
nice thx

**Comment by Rdelaura** [comment]
You know what would make a Monday awesome? If you released it :) . Cant wait man. Could def use some AI in my low pop server.

**Comment by Rdelaura** [comment]
It's Tuesday! Hopefully soon!

**Comment by taavipost** [comment]
how far thing are ?

**Comment by Rdelaura** [comment]
indeed. How is it going?

**Comment by dayzai** [comment]
Development is ongoing. Right now I'm developing A3EAI and A3XAI in parallel, so my workload is basically doubled. Creating HC-compatible features further doubles this workload, so it's basically a quadrupled workload.

The road to an actual release is unclear at the moment. The following things need to happen with *approximate* time requirements:

1. A3XAI shows no bugs or unexpected behavior during my testing, and 7 days pass with no bugs or issues found.
2. A3XAI opened to limited testing, and 7 days pass with no bugs or issues.
3. Exile devs fix the issues that would impact A3XAI and other AI addons (time unknown).

I must stress that this is a loosely drawn out plan, and each time I respond to "how things are going" the response is slightly different because things are changing every day.

**Comment by Rdelaura** [comment]
Ahhhh.  Well I appreciate your hard work. We're all looking forward to this release when it happens. I run a 30 pop server so dynamic AI completes the missing gap between me and a big server. 

Ronnie J DeLaura

**Comment by taavipost** [comment]
dayzai, i would be happy to participate in beta testing,

**Comment by disto1978** [comment]
A3EAI for Exile would be great! ...in my opinion Exile will get one of the most popular mods for Arma, much better than Epoch. Gameplay of Exile feels great and if there are scripts like A3EAI and maybe some convoys our PvE servers will go over to Exile.

Can´t wait for your release, thanks very much for spending your spare time!!!

**Comment by donkeypunchepoch** [comment]
Yes thanks a lot for all your hard work for years now!!!!!!!!

**Comment by nerdalertdk** [comment]
Hi,

if you need an beta tester let me know :D

**Comment by Rdelaura** [comment]
I check that github link daily, lol. So close to release, I can feel it!

**Comment by Almogavar** [comment]
Waiting ;D

**Comment by moosemilker** [comment]
Thanks for release of A3XAI: https://github.com/dayzai/A3xAI

GG!
